### ISSUE TITLE
python ./scripts/rmats_long.py error

### ISSUE THREAD

**Issue by Yumy526** [Xinglab/rMATS-long#18]
My files are all complete，but error happened
my code:
python /public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long.py --abundance /public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_abundance.esp  --updated-gtf /public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_updated.gtf  --gencode-gtf /public/home/ymwang/PacBio/6_bambu/mm10.ncbiRefSeq.gtf  --group-1 /public/home/ymwang/PacBio/8_rMats/group_1.txt --group-2 /public/home/ymwang/PacBio/8_rMats/group_2.txt --group-1-name 2cellA  --group-2-name 2cellB  --out-dir /public/home/ymwang/PacBio/7_isoform/resultpart/rMats/  --plot-file-type .png

my group_1.txt:
2cell_10A,2cell_11A,2cell_13A
my group_2.txt:
2cell_10B,2cell_11B,2cell_13B

my samples.tsv.updated:
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13B.sam	2cell_13
	5
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11A.sam	2cell_11
	2
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13A.sam	2cell_13
	4
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10A.sam	2cell_10
	0
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10B.sam	2cell_10
	1
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11B.sam	2cell_11
	3

error：
running: ['/public/home/ymwang/miniconda3/envs/gra/bin/python', '/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py', '--abundance', '/public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_abundance.esp', '--out-dir', '/public/home/ymwang/PacBio/7_isoform/resultpart/rMats/', '--group-1', '/public/home/ymwang/PacBio/8_rMats/group_1.txt', '--group-2', '/public/home/ymwang/PacBio/8_rMats/group_2.txt', '--adj-pvalue', '0.05', '--delta-proportion', '0.1', '--num-threads', '1']
running: ['Rscript', '/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.R', '/public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_abundance.esp', '/public/home/ymwang/PacBio/7_isoform/resultpart/rMats/', '1', '/public/home/ymwang/PacBio/8_rMats/group_1.txt', '/public/home/ymwang/PacBio/8_rMats/group_2.txt']

Attaching package: ‘DRIMSeq’

The following object is masked from ‘package:base’:

    proportions

**Error** in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 1 did not have 4 elements
Calls: main ... read_tsv_with_rows_as_first_column -> <Anonymous> -> scan
Execution halted
Traceback (most recent call last):
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py", line 150, in <module>
    main()
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py", line 146, in main
    detect_differential_isoforms(args)
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py", line 134, in detect_differential_isoforms
    detect_isoforms(script_dir, args.abundance, args.out_dir, args.num_threads,
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py", line 85, in detect_isoforms
    rmats_long_utils.run_command(command)
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long_utils.py", line 283, in run_command
    subprocess.run(command, check=True)
  File "/public/home/ymwang/miniconda3/envs/gra/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.R', '/public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_abundance.esp', '/public/home/ymwang/PacBio/7_isoform/resultpart/rMats/', '1', '/public/home/ymwang/PacBio/8_rMats/group_1.txt', '/public/home/ymwang/PacBio/8_rMats/group_2.txt']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long.py", line 653, in <module>
    main()
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long.py", line 646, in main
    summary = rmats_long(args)
              ^^^^^^^^^^^^^^^^
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long.py", line 608, in rmats_long
    detect_differential_isoforms(args.abundance, args.out_dir,
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long.py", line 293, in detect_differential_isoforms
    rmats_long_utils.run_command(command)
  File "/public/home/ymwang/tools/rMATS-long-main/scripts/rmats_long_utils.py", line 283, in run_command
    subprocess.run(command, check=True)
  File "/public/home/ymwang/miniconda3/envs/gra/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/public/home/ymwang/miniconda3/envs/gra/bin/python', '/public/home/ymwang/tools/rMATS-long-main/scripts/detect_differential_isoforms.py', '--abundance', '/public/home/ymwang/PacBio/7_isoform/resultpart/samples_N2_R0_abundance.esp', '--out-dir', '/public/home/ymwang/PacBio/7_isoform/resultpart/rMats/', '--group-1', '/public/home/ymwang/PacBio/8_rMats/group_1.txt', '--group-2', '/public/home/ymwang/PacBio/8_rMats/group_2.txt', '--adj-pvalue', '0.05', '--delta-proportion', '0.1', '--num-threads', '1']' returned non-zero exit status 1.

This is very important to me and would love to hear from you

**Comment by Yumy526** [comment]
It has been running smoothly, thanks for the help
