### ISSUE TITLE
About  rmats_long.py

### ISSUE THREAD

**Issue by border-info-nt** [Xinglab/rMATS-long#26]
Hello,

I've completed the analysis with ESPRESSO and am now planning to proceed with rMATS-long analysis. However, I generated the .esp and updated.gtf files individually for each sample, so I’m unable to perform a multi-sample analysis. Is it acceptable to merge these files, or should I start the analysis from scratch?

**Comment by EricKutschera** [comment]
Ideally the espresso run would include all of your samples and the `.esp` from espresso would then have all the sample names as columns. When you run espresso you can list the sample names along with the input files in the `samples.tsv` file described in the README: https://github.com/Xinglab/espresso/tree/v1.5.0?tab=readme-ov-file#basic-usage

It's not easy to merge the results from multiple espresso runs since the novel isoforms detected would have different IDs (`ESPRESSO:chr1:2:3`). Also there may be novel isoforms which have slightly different transcript start or end coordinates between runs but are otherwise the same

**Comment by border-info-nt** [comment]
Sorry,,,,

I have an additional question.
I received a force close error message.
The file male_N2_R0_updated.gtf is 99.1 MB
The file male_N2_R0_abundance.esp is 15.2MB.

We would appreciate your advice.
Thank you.


> 1: Vectorized input to `element_text()` is not officially supported.
> ℹ Results may be unexpected or may change in future versions of ggplot2. 
> 2: Removed 132 rows containing missing values or values outside the scale range (`geom_point()`). 
> 3:  get_plot_component(plot, "guide-box") で: 
>   Multiple components found; returning the first one. To return all, use `return_all = TRUE`.
> 4: Removed 132 rows containing missing values or values outside the scale range (`geom_point()`). 
> running: ['/miniconda3/bin/python', '/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py', '--updated-gtf', '/variant/male4/rmats_long_n1y594i8_tmp/ENSG00000131469.15_updated.gtf', '--out-tsv', '/西村/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12.tsv', '--main-transcript-id', 'ENST00000589913.6', '--second-transcript-id', 'ENST00000253788.12']
> running: ['/miniconda3/bin/python', '/rMATS-long_v_1_0_0/scripts/FindAltTSEvents.py', '-i', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12guif3i92_tmp_isoform.gtf', '-o', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12.tsv']
> Traceback (most recent call last):
>   File "/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py", line 176, in <module>
>     main()
>   File "/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py", line 172, in main
>     classify_isoform_differences(args)
>   File "/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py", line 55, in classify_isoform_differences
>     classify_isoform_differences_with_temp_files(
>   File "/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py", line 149, in classify_isoform_differences_with_temp_files
>     rmats_long_utils.run_command(command)
>   File "//rMATS-long_v_1_0_0/scripts/rmats_long_utils.py", line 278, in run_command
>     subprocess.run(command, check=True)
>   File "/miniconda3/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/miniconda3/bin/python', '/rMATS-long_v_1_0_0/scripts/FindAltTSEvents.py', '-i', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12guif3i92_tmp_isoform.gtf', '-o', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12.tsv']' died with <Signals.SIGKILL: 9>.
> Traceback (most recent call last):
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 624, in <module>
>     main()
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 618, in main
>     summary = rmats_long(args)
>               ^^^^^^^^^^^^^^^^
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 607, in rmats_long
>     process_genes(genes_to_process, temp_dir, sorted_paths,
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 103, in process_genes
>     process_genes_with_handles(
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 144, in process_genes_with_handles
>     process_gene(gene, temp_files_for_gene['abundance'],
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 251, in process_gene
>     classify_isoforms(gene_id, out_dir, updated_gtf, gencode_gtf,
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long.py", line 334, in classify_isoforms
>     rmats_long_utils.run_command(command)
>   File "/rMATS-long_v_1_0_0/scripts/rmats_long_utils.py", line 278, in run_command
>     subprocess.run(command, check=True)
>   File "/miniconda3/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/miniconda3/bin/python', '/rMATS-long_v_1_0_0/scripts/classify_isoform_differences.py', '--updated-gtf', '/variant/male4/rmats_long_n1y594i8_tmp/ENSG00000131469.15_updated.gtf', '--out-tsv', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12.tsv', '--main-transcript-id', 'ENST00000589913.6', '--second-transcript-id', 'ENST00000253788.12']' returned non-zero exit status 1.

**Comment by EricKutschera** [comment]
It looks like the main error was:
```
subprocess.CalledProcessError: Command '['/miniconda3/bin/python', '/rMATS-long_v_1_0_0/scripts/FindAltTSEvents.py', '-i', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12guif3i92_tmp_isoform.gtf', '-o', '/variant/male4/ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12.tsv']' died with <Signals.SIGKILL: 9>.
```

I was able to run FindAltTSEvents.py for those two transcripts based on the gencode v46 gtf and got this output:
```
transcript1	transcript2	event	coordinates
ENST00000253788.12	ENST00000589913.6	RI	chr17:42998472:42998748:+
```

I don't know why that command would get a SIGKILL. It may have been due to something else happening on your system. If you run rmats_long.py again do you get the same error for the same two transcript IDs?

**Comment by EricKutschera** [comment]
If you replace `os.remove(temp_file)` with `pass` at this line: https://github.com/Xinglab/rMATS-long/blob/v1.0.0/scripts/classify_isoform_differences.py#L61

Then if you run the `rmats_long.py` command again it will not delete the file like `ENSG00000131469.15_isoform_differences_ENST00000589913.6_to_ENST00000253788.12guif3i92_tmp_isoform.gtf` used in the `FindAltTSEvents.py` command shown in the error message. When you have that tmp gtf file you can try the `FindAltTSEvents.py` and see if it gets a SIGKILL. If it does then can you post the tmp gtf file? Or if that doesn't reproduce the error can you post the `rmats_long.py` command you are using and the input files you are using with that command?
